name: Build Minecraft Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Скачиваем ваш код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем правильную версию Java (JDK 8)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # Шаг 3: Даем право на запуск скрипту сборки (для Linux-систем на GitHub)
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Шаг 4: Собираем мод с помощью Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Шаг 5: Загружаем готовый .jar файл как артефакт (ИСПРАВЛЕНАЯ ВЕРСИЯ)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleClickerMod-JAR
          path: build/libs/*.jar
