name: Build Minecraft Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Скачиваем ваш код
      - name: Checkout repository
        uses: actions/checkout@v4

      # ДИАГНОСТИЧЕСКИЙ ШАГ: Показываем все файлы в проекте
      - name: List files in the repository
        run: ls -R

      # Шаг 2: Устанавливаем Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # Шаг 3: Даем права на запуск скрипту
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Шаг 4: Собираем мод (без перехода в папку)
      - name: Build with Gradle
        run: ./gradlew build

      # Шаг 5: Загружаем артефакт (из стандартного пути)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleClickerMod-JAR
          path: build/libs/*.jar
